version: '3.6'
services:
  nginx:
    build:
      context: docker/dev
      dockerfile: nginx.docker
    volumes:
      - ./app:/app
    depends_on:
      - php-fpm
    ports:
      - "8200:80"
    networks:
      - four
  php-fpm:
    build:
      context: docker/dev
      dockerfile: php-fpm.docker
    volumes:
      - ./app:/app
    depends_on:
      - db
      - mailer
    networks:
      - four
  php-cli:
    build:
      context: docker/dev
      dockerfile: php-cli.docker
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003 remote_enable=1
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - db
      - mailer
    volumes:
      - ./app:/app
      - composer:/root/.composer/cache
    networks:
      - four
  db:
    image: postgres:13.2-alpine
    volumes:
      - ./docker/postgres/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - "8201:5432"
    networks:
      - four
  mailer:
    image: mailhog/mailhog
    ports:
      - "8202:8025"

volumes:
  db:
  composer:

networks:
  four:
    driver: bridge
