version: '3.6'
services:
  nginx:
    build:
      context: docker/dev
      dockerfile: nginx.docker
    volumes:
      - ./app:/app
    depends_on:
      - php-fpm
    ports:
      - "8200:80"
    networks:
      - four
  php-fpm:
    build:
      context: docker/dev
      dockerfile: php-fpm.docker
    volumes:
      - ./app:/app
    depends_on:
      - db
      - mailer
      - redis
    networks:
      - four
  php-cli:
    build:
      context: docker/dev
      dockerfile: php-cli.docker
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003 remote_enable=1
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - db
      - mailer
      - redis
    volumes:
      - ./app:/app
      - composer:/root/.composer/cache
    networks:
      - four
  node:
    image: node:16.2-alpine
    volumes:
      - ./app:/app
    working_dir: /app
  node-watch:
    image: node:11.13-alpine
    volumes:
      - ./app:/app
    working_dir: /app
    command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && npm run watch"
  db:
    image: postgres:13.2-alpine
    volumes:
      - ./docker/postgres/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - "8201:5432"
    networks:
      - four
  mailer:
    image: mailhog/mailhog
    ports:
      - "8202:8025"
    networks:
      - four
  redis:
    image: redis
    restart: always
    ports:
      - "8203:6379"
    volumes:
      - ./docker/dev/redis:/data
    command: redis-server --requirepass secret
    networks:
      - four
volumes:
  db:
  composer:
  redis:

networks:
  four:
    driver: bridge
